name: deploy-puzzle

on:
  push:
    branches:
      - master
    paths:
      - "puzzle/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd puzzle && docker build -t registry.purplebear.io/prpo-puzzle-app-puzzle -f Dockerfile .
      - name: Push
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          echo "$REGISTRY_PASSWORD" | docker login registry.purplebear.io -u $REGISTRY_USERNAME --password-stdin
          docker push registry.purplebear.io/prpo-puzzle-app-puzzle
